# Generated by Django 4.0.5 on 2022-06-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('application_status', models.CharField(choices=[('application_complete', 'Application Complete'), ('application_fail', 'Application Fail'), ('document_pass', 'Document Pass'), ('final_pass', 'Final Pass')], default='application_complete', max_length=200)),
                ('job_positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.position')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='ResumeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('applications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('resumes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
            options={
                'db_table': 'resume_application',
            },
        ),
    ]
