# Generated by Django 4.0.5 on 2022-06-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('under_recruitment', 'Under Recruitment'), ('recruitment_ended', 'Recruitment Ended'), ('deleted', 'Deleted')], default='under_recruitment', max_length=200),
        ),
    ]
